name: Deploy Billing Engine

on:
  push:
    branches: [ "master" ]

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
  ECS_CLUSTER: billing-engine-cluster

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Build docker container and
        # push it to ECR
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Billing service task definition
      id: api-task
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: .aws/billing-service-task.json
        container-name: billing-service
        image: ${{ steps.build-image.outputs.image }}

    - name: Deploy billing service
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.api-task.outputs.task-definition }}
        service: billing-service
        cluster: ${{ env.ECS_CLUSTER }}
        wait-for-service-stability: true

    - name: Publish worker task definition
      id: outbox-task
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: .aws/outbox-worker-task.json
        container-name: outbox-worker
        image: ${{ steps.build-image.outputs.image }}

    - name: Deploy publish worker
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.outbox-task.outputs.task-definition }}
        service: outbox-worker
        cluster: ${{ env.ECS_CLUSTER }}
        wait-for-service-stability: true

    - name: Publish consumer task definition
      id: consumer-task
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: .aws/consumer-worker-task.json
        container-name: consumer-worker
        image: ${{ steps.build-image.outputs.image }}

    - name: Deploy consumer worker
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.consumer-task.outputs.task-definition }}
        service: consumer-worker
        cluster: ${{ env.ECS_CLUSTER }}
        wait-for-service-stability: true
